version: '3.7'

services:
  dai-book-viewer:
    build:
      context: .
    image: dainst/cilantro-dai-book-viewer
    ports:
      - "2222:80"
    volumes:
      - ./dai-book-viewer:/dai_book_viewer
      - ./sample:/usr/share/nginx/html/documents
      - ./annotations:/usr/share/nginx/html/annotations